name = "bugTDX"
default_targets = ["win32", "win64"]
build_directory = "C:\Users\orlsc\OneDrive\Documents\Builds"

love_files = [
    "+*",
    "-*/.*",
    "-./C:\Users\orlsc\OneDrive\Documents\Builds/*",
]
